import { LockKeyhole } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getAuditEvents } from "@/data/audit";
import { formatDateTime, roleLabels } from "@/lib/format";

export default async function AuditPage() {
  const events = await getAuditEvents();
  return <div className="space-y-6"><PageHeader eyebrow="Evidence record" title="Audit trail" description="Append-only application events for revision creation, decisions, issue, acknowledgement, and closure." /><div className="flex items-center gap-2 rounded-md border border-sky-200 bg-sky-50 p-3 text-sm text-sky-950"><LockKeyhole className="size-4" /><span>Normal application users cannot edit or delete these audit events.</span></div><div className="overflow-hidden rounded-lg border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead className="bg-muted/60 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Time</th><th className="px-4 py-3 font-medium">Action</th><th className="px-4 py-3 font-medium">Actor</th><th className="px-4 py-3 font-medium">Controlled item</th><th className="px-4 py-3 font-medium">Details</th></tr></thead><tbody className="divide-y">{events.map((event) => <tr key={event.id} className="align-top hover:bg-muted/30"><td className="px-4 py-3 whitespace-nowrap text-muted-foreground">{formatDateTime(event.createdAt)}</td><td className="px-4 py-3 font-medium capitalize">{event.action.replaceAll("_", " ").toLowerCase()}</td><td className="px-4 py-3 whitespace-nowrap">{event.actor ? <>{event.actor.name}<p className="text-xs text-muted-foreground">{roleLabels[event.actor.role]}</p></> : "System"}</td><td className="px-4 py-3"><p className="font-mono text-xs font-semibold">{event.drawing?.number ?? event.entityType}</p><p className="text-xs text-muted-foreground">{event.project?.code ?? "—"}{event.revision ? ` · Rev ${event.revision.revisionCode}` : ""}</p></td><td className="max-w-sm px-4 py-3 font-mono text-[11px] text-muted-foreground"><span className="line-clamp-3">{event.details ? JSON.stringify(event.details) : "—"}</span></td></tr>)}</tbody></table></div><div className="border-t px-4 py-3 text-xs text-muted-foreground">Showing the latest {events.length} events</div></div></div>;
}

